binds:
- port: 3000
  listeners:
  - routes:
    - backends:
      - mcp:
          targets:
          - name: everything
            stdio:
              cmd: npx
              args:
              - '@modelcontextprotocol/server-everything'
      policies:
        extAuthz:
          host: localhost:9000
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - mcp-protocol-version
          - content-type
          - cache-control
          - '*'
          - authorization
    - hostnames:
      - example.com
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: test
      ruleName: rule-1
